### PR TITLE
Parallel runner implementation

### PR DESCRIPTION
**Pull request by tomconte**
This is an implementation for #58.

/cc @giventocode

### CODE REVIEW

**Review by giventocode — COMMENTED** [review]
Overall looks good. A few comments regarding the API and naming. Thanks for this!

**Comment by tomconte** [comment]
Thanks for your feedback @giventocode ! Makes sense to me. I just pushed the changes.

**Comment by giventocode** [comment]
Thanks @tomconte, one last thing. Can you change the target branch to develop?

**Comment by tomconte** [comment]
Thanks @giventocode, just changed the target branch.

**Pull request merged**
